# Title of your blog; shows in the header
name: "katabaticwind's blog"

# Description of your content (will only be used on Google Search)
description: "Research and development blog"

# Your name. Will show in your footer + sidebar
author: "Anonymous"

url: "https://katabaticwind.github.io"
# baseurl: "/blog"

# A short presentation of yourself. Will show in the sidebar, under your name. Best usage would be between 30 to 50 words.
author-bio: "I'm a data scientist and machine learning researcher."

# Social Accounts (mine, as placeholders)
# twitter: katabaticwind
github: katabaticwind

# Google Analytics (you may want to changes these with yours or even delete :)
ga_domain: katabaticwind.github.io
# ga_tracking_id: UA-47727049-1

# Other (refer to http://jekyllrb.com/docs/home/ for further details on the below)
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
paginate: 10
paginate_path: "/page/:num"

# SCSS
sass:
  sass_dir: _scss
  style: :compressed
